name: task_cli
description: >
  Application CLI de gestion de tâches en Dart pur (sans Flutter), avec
  persistance JSON, classes abstraites, héritage, génériques et exceptions
  personnalisées.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
